/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forma;

import Controller.Controller;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Alat;
import model.Inzenjer;
import model.Lokacija;
import model.Masina;
import model.TipMasine;

/**
 *
 * @author tesic
 */
public class FormaZaUnos extends javax.swing.JFrame {
    private List<Lokacija> lokacije;

    /**
     * Creates new form FormaZaUnos
     */
    public FormaZaUnos() {
        initComponents();
        popuniComboBox();
        
        ModelTabeleAlat mta = new ModelTabeleAlat();
        jTableAlat.setModel(mta);
        Date danas = new Date();
        int g,d,m;
        Calendar kalendar = Calendar.getInstance();
        kalendar.setTime(danas);
        g = kalendar.get(Calendar.YEAR);
        m =kalendar.get(Calendar.MONTH+1);
        d = kalendar.get(Calendar.DAY_OF_MONTH);
        
        String datum = d+"."+m+"."+g+".";
        jTextFieldDatum.setText(datum);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldProizvodjac = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDatum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxTipMasine = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxLokacija = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlat = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxAlat = new javax.swing.JComboBox<>();
        jButtonDodaj = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jButtonSacuvajMasinu = new javax.swing.JButton();
        jTextFieldGodPR1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldRadniVek = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Naziv");

        jLabel2.setText("Godina proizvodnje");

        jLabel3.setText("Datum");

        jLabel4.setText("Tip masine");

        jLabel5.setText("Lokacija");

        jTableAlat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableAlat);

        jLabel6.setText("Alat");

        jButtonDodaj.setText("Dodaj");
        jButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajActionPerformed(evt);
            }
        });

        jButtonObrisi.setText("Obrisi");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jButtonSacuvajMasinu.setText("Sacuvaj masinu");
        jButtonSacuvajMasinu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajMasinuActionPerformed(evt);
            }
        });

        jLabel7.setText("Proizvodjac");

        jLabel8.setText("Radni vek");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldGodPR1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldRadniVek, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxTipMasine, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxLokacija, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonDodaj))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSacuvajMasinu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldGodPR1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRadniVek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxTipMasine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBoxAlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDodaj))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonObrisi)
                                .addGap(166, 166, 166)
                                .addComponent(jButtonSacuvajMasinu)
                                .addGap(13, 13, 13))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jComboBoxLokacija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajActionPerformed
        Alat a = (Alat) jComboBoxAlat.getSelectedItem();
        if(a.getStanje()>0){
        ModelTabeleAlat mta = (ModelTabeleAlat) jTableAlat.getModel();
        mta.dodajAlat(a);
        a.setStanje(a.getStanje()-1);
        }else{
            JOptionPane.showMessageDialog(null, "NEMA NA STANJU");
        }
        
    }//GEN-LAST:event_jButtonDodajActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        int selektovaniRed = jTableAlat.getSelectedRow();
        if(selektovaniRed == -1){
            JOptionPane.showConfirmDialog(null, "Greska");
             }else{
            ModelTabeleAlat mta = (ModelTabeleAlat) jTableAlat.getModel();
            mta.obrisi(selektovaniRed);
        }
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jButtonSacuvajMasinuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajMasinuActionPerformed

        try {
        Inzenjer ulogovani = Controller.getInstance().getUlogovani();
        String imePrezime = ulogovani.getIme()+" "+ulogovani.getPrezime();
        String naziv = jTextFieldNaziv.getText();
        String proizvodjac = jTextFieldProizvodjac.getText();
        int radniVek = Integer.parseInt(jTextFieldRadniVek.getText());
        int godPr = Integer.parseInt(jTextFieldProizvodjac.getText());
        if(godPr <1900 || godPr>2018){
            JOptionPane.showConfirmDialog(null, "GRESKA godina proizvodnje");
            return;
        }
        TipMasine tip = (TipMasine) jComboBoxTipMasine.getSelectedItem();
        Lokacija lokacija = (Lokacija) jComboBoxLokacija.getSelectedItem();
        int idLokacija = lokacija.getId();
        boolean postojiMasinaNaLokaciji = Controller.getInstance().postojiMasina(idLokacija);
        if(postojiMasinaNaLokaciji){
            JOptionPane.showMessageDialog(null, "GRESKA MASINA");
            return;
        }
        SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy");
        Date datum = format.parse(jTextFieldDatum.getText());
        
        if(datum.before(new Date())){
          JOptionPane.showMessageDialog(this, "GRESKA DATUM");
          return;
        }
        
        Masina m = new Masina(-1, naziv, datum, godPr, radniVek, proizvodjac, tip, lokacija, imePrezime);
        ModelTabeleAlat mta = (ModelTabeleAlat) jTableAlat.getModel();
        List<Alat> alati = mta.getAlati();
        m.setAlati(alati);
        boolean uspesno = Controller.getInstance().ubaciMasinuUBazu(m);
         
        
        } catch (ParseException ex) {
            Logger.getLogger(FormaZaUnos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonSacuvajMasinuActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonSacuvajMasinu;
    private javax.swing.JComboBox<Alat> jComboBoxAlat;
    private javax.swing.JComboBox<Lokacija> jComboBoxLokacija;
    private javax.swing.JComboBox<TipMasine> jComboBoxTipMasine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAlat;
    private javax.swing.JTextField jTextFieldDatum;
    private javax.swing.JTextField jTextFieldGodPR1;
    private javax.swing.JTextField jTextFieldNaziv;
    private javax.swing.JTextField jTextFieldProizvodjac;
    private javax.swing.JTextField jTextFieldRadniVek;
    // End of variables declaration//GEN-END:variables

    private void popuniComboBox() {
        for(TipMasine tm: TipMasine.values()){
            jComboBoxTipMasine.addItem(tm);
        }
        
       List<Lokacija> sveLokacije = Controller.getInstance().vratiSveLokacijeIzBaze();
       
       for(Lokacija l: sveLokacije){
           jComboBoxLokacija.addItem(l);
       }
       
       List<Alat> sviAlati = Controller.getInstance().vratiSveAlate();
       for(Alat a: sviAlati){
           jComboBoxAlat.addItem(a);
       }
       
       
    }
}
